Product, ProductOption 관련 기능 추가
movie42/kiosk-backend pull request #16
Opened 2022-05-13 17:13 UTC by minsoo0715

# 개요
Product, ProductOption 관련 기능 추가

## 작업 내용
- 여러 개를 추가/수정 하는 경우에는 boolean 타입의 배열을 통해 각각의 성공 여부를 반환합니다.
- products() : store의 상품들을 반환, 옵션들도 같이 반환
- addProducts() : 상품 추가
- editProducts() : 상품 수정
- deleteProducts() : 상품 삭제
- addProductOptions() : 상품 옵션 추가
- editProductOptions() : 상품 옵션 수정
- deleteProductOptions() : 상품 옵션 삭제
- product 엔티티에 options에 Field 어노테이션 추가
- ProductRepository.getProductsByStoreId에서 find 두번째 옵션으로 relations 추가

## 스크린샷
필요하다면 첨부해주세요.

pull requests 내용을 작성하실때 'resolve: #[이슈넘버]'를 넣어주시면 merge될 때, 깃허브에서 자동으로 이슈를 close해줍니다.

2022-05-13 17:59 UTC, tjsry0466 requested changes
리뷰 확인 부탁드립니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  @IsNumber()
`@IsInt`로 통일해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  @Field()
number 타입은 () => Int로 Int 스칼라 타입 지정해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  imageUrl: string;
url이 없을 수도 있을 것 같습니다.
optional인 컬럼들 적용해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
> +  @Field(() => [Option])
관계에는 @Field를 붙이지 않아도 됩니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.module.ts
> +  imports: [TypeOrmModule.forFeature([ProductRepository]), TypeOrmModule.forFeature([ProductOptionRepository])],
TypeOrmModule은 하나만 사용하고 리스트 안에 배열로 넣어주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  @Query(() => [Product], { nullable: 'items' })
item은 null을 허용하지 않아도 될 것 같습니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  async addProducts(@Args({ name: 'products', type: () => [AddProductInput] }) args: AddProductInput[]) {
단일값이 아니거나 라인이 길어지는경우 dto를 사용해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  @Mutation(() => [Boolean])
결과는 true, false만 반환하면 될것같습니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +    return await this.productService.editProducts(args);
return에는 await을 명시하지 않아도 됩니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +        suc.push(await this.productRepository.addProduct(product));
await은 함수의 인자에서 사용하지말아주세요
따로 선언후에 사용해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +      const cnt: number = await this.productRepository.getProductsNumberByStoreIdAndName(product.storeId, product.name);
암묵적으로 타입이 정해지는 변수에는 타입을 명시적으로 적어주지 않아도됩니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +  async addProducts(products: IAddProduct[]) {
앞서 말씀드린대로 결과값을 배열로 전달하지 않아도됩니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +  }
마찬가지입니다 성공 실패 결과만 반환해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +  async deleteProducts(keys: number[]) {
`keys`가 명확하지 않은 것 같습니다 명확한 네이밍으로 적어주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +    return suc;
동일합니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +  }
동일합니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +      const cnt = await this.productRepository.count({ where: { id: option.productId } });
DB접근은 레포지토리 레이어에서 해주세요

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/product.service.ts
> +    return suc;
동일합니다

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsByStoreId(_storeId: number) {
`_` 를 붙인 이유가 있나요?

2022-05-13 17:59 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
함수의 이름과 동작이 일치하지 않은 것 같습니다

2022-05-14 02:29 UTC, minsoo0715 commented on src/product/entity/product.entity.ts
> +  @Field(() => [Option])
product 서비스의 products()에서 Option들까지 한번에 받아오려고 추가한건데, 그냥 products() 에서 Option 레포지토리를 불러와야 할까요?

2022-05-14 02:31 UTC, minsoo0715 commented on src/product/product.resolver.ts
> +  @Mutation(() => [Boolean])
요청 값이 여러 개이니까, 각각의 성공 여부를 반환하는 건데, 만약 한 개라도 실패하면 false를 반환해야할까요?

2022-05-14 02:36 UTC, minsoo0715 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
getNumberOfProductsWithDuplicateNameInStore 으로 수정하겠습니다. 아니면 더 좋은 아이디어가 있으실까요?

2022-05-14 02:36 UTC, minsoo0715 commented on src/product/repository/product.repository.ts
> +  async getProductsByStoreId(_storeId: number) {
object의 key 값과 구분하려고 붙였습니다. 그냥 언더바를 제거할까요?

2022-05-14 05:42 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
number가 수량을 나타내는 표현은 아닌것 같습니다 amount가 괜찮을 것 같네요

2022-05-14 05:42 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
storeId랑 name을 같이 받아야하는 이유가있나요?

2022-05-14 05:43 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsByStoreId(_storeId: number) {
제거해도 문제없어 보입니다

2022-05-14 05:43 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  @Mutation(() => [Boolean])
실패하면 에러가 날것 같네요

2022-05-14 05:44 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
> +  @Field(() => [Option])
음 이부분은 확인이 필요할것같네요
relations로 가져올때 필요한 부분이면 붙여도됩니다

2022-05-14 05:44 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
> +  @Field(() => [Option])
querybuilder로 사용할지 다른 메소드를 사용할지도 정해야될것 가텐요

2022-05-14 05:52 UTC, minsoo0715 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
해당 store에 같은 name을 가지는 Product가 존재하면 안된다고 요구사항에 적혀 있길래. 해당 Store에 해당 name을 가지는 Product가 있는지 확인하려고 추가한 메소드입니다.

2022-05-14 05:53 UTC, minsoo0715 commented on src/product/entity/product.entity.ts
> +  @Field(() => [Option])
네 그럼 일단은 위 형태로 남겨놓겠습니다.

2022-05-14 05:54 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
`existsStoreProductByName(storeId: number, name: string)` 으로 네이밍하고 결과만 true false로 리턴해주면 될 것 같습니다

2022-05-14 05:56 UTC, minsoo0715 commented on src/product/dto/add-product.input.ts
> +  @Field()
그럼 그냥 IsNumber()를 IsInt()로 통합하면 스칼라 타입 지정해줄 필요가 없을까요? 아니면 IsInt도 동일하게 스칼라 타입 지정해주어야 할까요?

2022-05-14 05:57 UTC, minsoo0715 commented on src/product/repository/product.repository.ts
> +  async getProductsNumberByStoreIdAndName(_storeId: number, _name: string) {
넵 알겠습니다.

2022-05-14 05:58 UTC, tjsry0466 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
@IsInt 적용하면 IsNotEmpty를 적용하지 않아도 빈값도 막아지는지 확인 부탁드릴게요

2022-05-14 05:59 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  @Field()
지정 해주어야 합니다 해당 타입은 Int이고 number는 float입니다

2022-05-14 06:00 UTC, minsoo0715 commented on src/product/dto/add-product.input.ts
> +  @Field()
넵 알겠습니다

2022-05-14 06:18 UTC, tjsry0466 commented on src/product/repository/product-option.repository.ts
> +  async editOption(option: IEditOption) {
CRUD는 add, get, update, remove로 사용하려고 하는데 이견 없으시면 수정 부탁드립니다

2022-05-14 06:35 UTC, minsoo0715 commented on src/product/product.resolver.ts
> +  async addProducts(@Args({ name: 'products', type: () => [AddProductInput] }) args: AddProductInput[]) {
어떤 형태로 변경해야 할까요? AddProductInput 자체를 배열 형태로 변경해야 할까요?

2022-05-14 07:01 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  async addProducts(@Args({ name: 'products', type: () => [AddProductInput] }) args: AddProductInput[]) {
아 배열형태로 받기 위해서 한거군요 그럼 문제 없는것같네요

2022-05-14 07:04 UTC, minsoo0715 commented on src/product/product.resolver.ts
> +  async addProducts(@Args({ name: 'products', type: () => [AddProductInput] }) args: AddProductInput[]) {
넵 알겠습니다.

2022-05-14 07:19 UTC, minsoo0715 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
확인해봤는데 @IsInt() 뿐만 아니라 @IsString() 같이 Type Validation Decorator들을 적용하면 빈 값이 들어오면 에러를 던집니다.

2022-05-14 07:20 UTC, tjsry0466 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
그럼 @IsNotEmpty는 없어도 될 것 같습니다

2022-05-14 07:20 UTC, minsoo0715 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
타입이 다른 값이 들어오거나 값이 아예 안들어오는 경우 모두 타입이 다르다는 에러를 던지네요.

2022-05-14 07:21 UTC, tjsry0466 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
null과 undefined도 다른 타입이니 맞는 것 같습니다

2022-05-14 07:22 UTC, minsoo0715 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
IsString() IsInt() 모두 IsNotEmpty()를 제외할까요?

2022-05-14 07:22 UTC, tjsry0466 commented on src/product/dto/add-product-option.input.ts
> +  @IsInt()
네 필요없어 보입니다

2022-05-14 14:43 UTC, tjsry0466 commented
@minsoo0715 컨플릭트 해결해주세요

2022-05-14 14:44 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +    return cnt != 0;
count > 0 으로 바꿔주세요

2022-05-14 14:45 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
쿼리 한번만 날릴수 있도록 해주세요

2022-05-14 14:45 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
마찬가지입니다

2022-05-14 14:45 UTC, tjsry0466 commented on src/product/product.service.ts
> +    return true;
마찬가지입니다

2022-05-14 14:45 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
마찬가지입니다

2022-05-14 14:45 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
마찬가지입니다

2022-05-14 14:47 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  imageUrl: string;
field랑 validation 옵션이랑 통일해주세요

2022-05-14 15:55 UTC, tjsry0466 commented on src/product/dto/add-product-option.input.ts
> +  productId: number;
productId를 첫번째 인수로 정의해주세요

2022-05-14 15:55 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  storeId: number;
storeId를 첫번쨰 인수로 정의해주세요

2022-05-14 15:56 UTC, tjsry0466 commented on src/product/dto/edit-product.input.ts
> +  id: number;
id를 바꿀일은 없을 것 같습니다

2022-05-14 15:56 UTC, tjsry0466 commented on src/product/interface/add-option.interface.ts
> +  productId: number;
마찬가지로 순서 바꿔주세요

2022-05-14 15:58 UTC, tjsry0466 requested changes
리뷰 확인 부탁드립니다
이전에 리뷰 드린 사항도 적용해주세요

2022-05-14 15:58 UTC, tjsry0466 commented on src/product/interface/add-product.interface.ts
> +  storeId: number;
마찬가지로 순서 바꿔주세요

2022-05-14 15:58 UTC, tjsry0466 commented on src/product/interface/edit-product.interface.ts
> +  id: number;
마찬가지로 id를 바꿀일은 없을 것 같습니다

2022-05-14 15:58 UTC, tjsry0466 commented on src/product/interface/edit-option.interface.ts
> +  id: number;
마찬가지로 바꿀일은 없을 것 같습니다

2022-05-15 08:41 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
길이가 1인 배열로 요청하면 쿼리 한번만 날릴 수 있지 않나요?

2022-05-15 08:42 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
옵션이 여러개면 여러개 쿼리가 날라가지않나요?

2022-05-15 08:42 UTC, minsoo0715 commented on src/product/dto/edit-product.input.ts
> +  id: number;
수정할 객체의 Id는 받아와야 하지 않을까요?

2022-05-15 08:43 UTC, tjsry0466 commented on src/product/dto/edit-product.input.ts
> +  id: number;
그러네요 
네이밍은 productId로 명시적으로 적어주는게 좋을 것 같습니다

2022-05-15 08:44 UTC, minsoo0715 commented on src/product/dto/edit-product.input.ts
> +  id: number;
넵 알겠습니다.

2022-05-15 08:46 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +    return cnt > 0;
변수명은 되도록이면 축약하지 말아주세요

2022-05-15 08:47 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
지금 resolver에서 옵션 배열을 받고 있는데 어떻게 수정해야할까요?

2022-05-15 08:48 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
현재 요구사항 상에는 상품 여러개를 한번에 추가/삭제/수정하는 것이 요구되어 있습니다.

2022-05-15 08:49 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
여러개의 상품을 각각 다른 옵션으로 변경하진 않을 것 같습니다
id만 배열로 받으면 될 것 같아요

2022-05-15 08:50 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
수정할때 id만 배열로 받으면 수정사항은 어떻게 반영되어야 하나요?

2022-05-15 08:51 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
아 여러 옵션들을 하나의 수정사항으로만 받게 하면 될까요?

2022-05-15 08:51 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
update set option = ? where id IN [1, 2, 3] 이런식으로 수정되면 됩니다

2022-05-15 08:53 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
그러면 상품 추가, 옵션 추가는 해당이 되지 않는 내용일까요? 같은 내용으로 추가되는 경우는 없을 것 같은데요.

2022-05-15 08:54 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
insert into item(field) values (1), (2) 이런식으로 한번에 여러개 아이템을 추가하는 쿼리를 날릴 수 있습니다

2022-05-15 08:55 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
지금 Option 수정은 product에 대한 옵션만을 수정하는 게 아니라. Option 객체만 수정하고 있습니다.

2022-05-15 08:57 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
option수정이면 option 서비스에 있어야 하지않을까요?

2022-05-15 09:09 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
현재 옵션은 단 하나에 product에 대해서만 관계를 가지고 있어서 product 서비스에 넣었습니다. option 서비스에 넣을까요?

2022-05-15 09:11 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
음.. 다시 생각해보니 그냥 product에서 하는게 좋아보이네요 option 모듈을 만들어놓지동 ㅏㄴㅎ았네요
option에 productId가 있으니 productId로 option을 직접 수정하면됩니다

2022-05-15 09:14 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
> insert into item(field) values (1), (2) 이런식으로 한번에 여러개 아이템을 추가하는 쿼리를 날릴 수 있습니다
Repository단에서 save, delete, update에 product나 option을 배열로 넣어도 되는 건가요? (delete의 경우 키 배열)

2022-05-15 09:16 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
어떤 의미인지잘 이해가 안되네요 edit이나 add시에 관계된 테이블에 상관없이 update, insert를 할 수 있습니다

2022-05-15 09:19 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
> update set option = ? where id IN [1, 2, 3] 이런식으로 수정되면 됩니다

상품의 경우에는 각자 다른 내용으로 추가 / 수정되는 경우가 있지 않을까요? `상품은 한번에 여러개를 등록할 수 있다.` `상품 관리 화면에서 선택한 다수의 상품을 한번에 수정할 수 있다.` 요구사항 내용입니다.

2022-05-15 09:21 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
설명이나 이름과 같은게 수정되는것이라면 한번에 한개만 수정되야되는게 맞는 것 같고
상태가 변경되는거라면 동일한 상태로 한번에 변경될 것 같습니다

2022-05-15 09:24 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
상태가 변경되는 경우가 예를 들어 어느 경우가 있을까요?

2022-05-15 09:24 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
상품을 활성화/비활성화 하는 기능이 있다면 해당될것 같습니다

2022-05-15 09:29 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
아 요구사항에 관련 내용은 없어서 update의 경우에는 설명/이름같은게 수정되는 걸로 서비스를 작성했습니다. 상품의 상태를 변경할 때에는  다른 서비스 메소드를 작성해서 새로운 Mutation을 따로 만드는 걸로 하는게 어떨까요?

2022-05-15 09:31 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
> 어떤 의미인지잘 이해가 안되네요 edit이나 add시에 관계된 테이블에 상관없이 update, insert를 할 수 있습니다

옵션이 Product에 n:1관계로 종속되어 있어 product service에서 처리해도 의미상 괜찮지 않을까해서 드린 말씀입니다. 그럼 그냥 옵션 서비스를 나누는 걸로 할까요?

2022-05-15 09:32 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
product service에서 처리해도 될것 같습니다

2022-05-15 09:32 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
이름/설명이 수정되는거라면 한번에 한개만 수정되는게 맞는 것 같습니다

2022-05-15 09:33 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
> 상품의 상태를 변경할 때에는 다른 서비스 메소드를 작성해서 새로운 Mutation을 따로 만드는 걸로 하는게 어떨까요?

맞습니다

2022-05-15 10:19 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
그럼 상품 / 옵션 수정은 단일 객체에 대해서만 수정하도록 변경하겠습니다.

2022-05-15 13:58 UTC, minsoo0715 commented
`edit-product-option.input.ts`의 `EditProductOptionInput`의 name validation 중에서 `IsOptional()` 제거 했습니다. 프로퍼티가 id말고는 하나라 name이 없는 요청은 의미가 없을 것 같습니다.

2022-05-15 14:01 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
한 store에 같은 name을 가진게 있는지 확인하는 로직때문에 그냥 배열 형태로 한번에 상품을 추가하거나, 상품옵션을 추가하기 힘들 것 같습니다. 아니면, 한 store에 같은 name을 못가지게 entitiy에서 제한을 걸 수 있는 방법이 있을까요?

2022-05-15 14:03 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
id로 하면되지않나요?

2022-05-15 14:05 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
id가 StoreId 말씀하시는 건가요?

2022-05-15 14:07 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
실제로 ProductId를 id로 가지는 상품이 존재하는지 여부를 판단해야하기 때문에 이 경우도 한번에 옵션 추가하기는 힘들 것 같습니다.

2022-05-15 14:10 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
아 한 가게에 같은 이름을 가진 상품이 있는지 제한하고 싶다는 말씀이신건가요?

2022-05-15 14:11 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
아 네 맞습니다. 요구사항에 `한 가게안에서 상품 이름은 중복되면 안된다.`라고 적혀있어서요

2022-05-15 14:24 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
프론트에서 따로 유효성 검사를 수행하는 로직을 넣는게 좋을수도 있을 것 같네요
근데 중복되도 상관없지 싶어요

2022-05-15 14:32 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
한번에 조회하고 존재하지 않으면 bad request exception을 반환해도 될 것 같습니다

2022-05-16 05:38 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
그냥 db 자체에서 storeId, Name 쌍에 대해서 유니크 조건을 걸도록 변경해서 커밋해봤습니다. 이 방법은 괜찮지 않을까요?

2022-05-16 05:39 UTC, minsoo0715 commented on src/product/product.service.ts
> +    }
일단 한번에 조회하는 로직은 구현하였는데, bad request exception 반환에 대해서는 조금 더 공부하고 적용시키겠습니다.

2022-05-16 05:40 UTC, minsoo0715 commented
@tjsry0466 그냥 db 자체에서 storeId, Name 쌍에 대해서 유니크 조건을 걸도록 변경해서 커밋해봤습니다. 이 방법은 괜찮지 않을까요?

2022-05-16 11:29 UTC, tjsry0466 commented
@minsoo0715 유니크 조건을 걸면 에러를 캐치해줘야 될 것 같네요

2022-05-16 11:30 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +    await this.repository.save(this.repository.create(this.repository.create(products)));
create가 두번 들어가있네요

2022-05-16 11:31 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +    return count == ids.length;
```suggestion
    await this.repository.count({ where: { id: In(ids) } });
    return true;
```

2022-05-16 11:32 UTC, tjsry0466 commented on src/product/product.service.ts
> +    }
early return을사용해주세요
else는 가능하면 쓰지 말아주세요

2022-05-16 11:32 UTC, tjsry0466 commented on src/product/product.service.ts
> +    return await this.productRepository.removeProducts(productIds);
await 제거해주세요

2022-05-16 11:33 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  async removeProductOptions(@Args({ name: 'option_id', type: () => [Number] }) args: number[]) {
dto로정의해주세요

2022-05-16 11:33 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  async removeProducts(@Args({ name: 'product_keys', type: () => [Number] }) args: number[]) {
마찬가지입니다

2022-05-16 11:33 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +    });
```suggestion
    return this.productService.updateProduct(arg.productId, arg);
```

2022-05-16 12:26 UTC, minsoo0715 commented on src/product/repository/product.repository.ts
> +    return count == ids.length;
이렇게하면 존재하는지 여부를 알 수 없지 않을까요?

2022-05-16 12:27 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +    return count == ids.length;
그러네요 비교만 ===로 바꾸면 될것 같습니다

2022-05-16 14:40 UTC, tjsry0466 commented on src/product/product.service.ts
> +    return await this.productOptionRepository.addOptions(options);
return 뒤에 await 제거해주세요

2022-05-16 14:45 UTC, minsoo0715 commented
> @minsoo0715 유니크 조건을 걸면 에러를 캐치해줘야 될 것 같네요

에러 캐치는 일단 임시방편으로 넣었습니다. 나중에 nest의 Excetion filter 사용해서 전체적으로 Error Handling 패턴을 구현하는게 좋을 것 같습니다.

2022-05-16 14:54 UTC, minsoo0715 commented on src/product/product.service.ts
> +    const isExistIds = this.productRepository.existProductByIds(productIds);
@tjsry0466 return하지 않고 그냥 값을 읽어오는 비동기 함수도 await을 사용하지 않아도 되는걸까요?

2022-05-16 15:01 UTC, tjsry0466 commented on src/product/product.service.ts
> +    const isExistIds = this.productRepository.existProductByIds(productIds);
얘는 해줘야됩니다

2022-05-16 15:54 UTC, minsoo0715 commented on src/product/product.service.ts
> +    const isExistIds = this.productRepository.existProductByIds(productIds);
수정했습니다 감사합니다.

2022-05-16 16:23 UTC, tjsry0466 commented on src/product/dto/remove-product-option.input.ts
> +  OptionIds: number[];
array관련 옵션도 적용해주세요

2022-05-16 16:24 UTC, tjsry0466 commented on src/product/product.resolver.ts
> +  // 소유자 권한 체크 필요
// TODO: 와 같이 작성해주세요

2022-05-17 00:19 UTC, minsoo0715 commented on src/product/dto/remove-product-option.input.ts
> +  OptionIds: number[];
@ArrayNotEmpty()만 추가로 적용시키면 될까요?

2022-05-17 13:22 UTC, tjsry0466 commented on src/product/dto/remove-product-option.input.ts
> +  OptionIds: number[];
@ArrayUnique도 필요할것같네요

2022-05-17 13:23 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  imageUrl?: string;
field에도 nullable 적용해주세요

2022-05-17 13:23 UTC, tjsry0466 commented on src/product/dto/add-product.input.ts
> +  description?: string;
마찬가지입니다

2022-05-17 13:24 UTC, tjsry0466 commented on src/product/dto/edit-product.input.ts
> +  price?: number;
int 스칼라 타입적용해주세요

2022-05-17 13:24 UTC, tjsry0466 commented on src/product/dto/remove-product.input.ts
> +  productIds: number[];
여기도 배열 관련 옵션 적용해주세요

2022-05-17 13:25 UTC, tjsry0466 commented on src/product/interface/edit-option.interface.ts
> +}
얘는 optionId 필요없나요?

2022-05-17 13:25 UTC, tjsry0466 commented on src/product/interface/edit-product.interface.ts
> +}
얘는 productId필요없나요?

2022-05-17 13:26 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +      Logger.error(e);
logger 객체 생성해서 작성해주세요

2022-05-18 13:37 UTC, minsoo0715 commented on src/product/interface/edit-option.interface.ts
> +}
resolver에서 서비스 `updateOption(optionId: number, option: IEditOption)`을 호출할때 dto에서 id랑 분리해서 넘깁니다.

2022-05-18 13:39 UTC, minsoo0715 commented on src/product/interface/edit-product.interface.ts
> +}
이것도 마찬가지로 resolver에서 서비스  `updateProduct(productId: number, product: IEditProduct)`을 호출할때 dto에서 id랑 분리해서 넘깁니다.

2022-05-19 01:47 UTC, minsoo0715 commented
product 엔티티에서도 imageUrl, description을 nullable로 설정했습니다. 이에 따른 migration 코드도 추가했습니다.

2022-05-19 11:26 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
> +  description?: string;
field에도 추가해주세요

2022-05-19 11:26 UTC, tjsry0466 commented on src/product/repository/product.repository.ts
> +      log.error(e);
문서 참고해서 클래스 이름 입력받아서 logger 객체 생성해주세요

2022-05-20 11:21 UTC, tjsry0466 approved these changes
리뷰 나온것만 수정해주세요

2022-05-20 17:08 UTC, minsoo0715 commented
마지막 두 리뷰도 완료했습니다. 꼼꼼한 리뷰 감사합니다.

2022-05-20 17:08 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
>    name: string;
옵셔널 적용이 다르네요

2022-05-20 17:08 UTC, merged

2022-05-20 17:09 UTC, tjsry0466 commented on src/product/entity/product.entity.ts
>    name: string;
@minsoo0715 reopen해서 적용해주세요

2022-05-20 17:23 UTC, minsoo0715 commented on src/product/entity/product.entity.ts
>    name: string;
#24 merge후 reopen 방법을 몰라 새로 pr열었습니다. 확인 부탁드립니다. @tjsry0466